mybatis:
  type-aliases-package: com.itdreamworks.datamanage.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  profiles:
    active: dev